### ISSUE TITLE
type define syntax

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/elz#130]
### TODOs

- [x] parse and generate basic struct syntax
    ```
    type Car = (
      name: string,
      price: int,
    )
    ```
- [x] correctly handle the type from others module(as binding, leading `_` private the type)
- [x] using user-defined type in code
- [ ] generic type inference
- [ ] implement multiple-type
    ```
    type Option 'a =
      Just('a)
      | Nothing
    ```

**Comment by dannypsnl** [comment]
- [x] parse and generate basic struct syntax
- [ ] correctly handle the type of others module
- [ ] implement multiple-type
    ```
    type Option 'a =
      Just('a)
      | Nothing
    ```
