### ISSUE TITLE
manual parser

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/elz#140]
### TODO:

- [x] binding
  - [x] name 3eef0645fa53e2a5c40e32d9f8bc53a20d5811c2
  - [x] parameters 3eef0645fa53e2a5c40e32d9f8bc53a20d5811c2
  - [x] expression 3eef0645fa53e2a5c40e32d9f8bc53a20d5811c2
  - [x] use `_` prefix as private function 5fc0d18d781f94dd50585311c98a62f6914be69a
  ~- [ ] separate global variable & the function without parameters~ do this at #133
~- [ ] type~ we just do it at #130 
- [x] import statement 1a4a2f86e1e0ca0fb6a2665330a1642d4bba98bd
- [x] binding type declaration 9a964475779dbf9393a47828b08afc9c5f33eca6
- [x] expression
  - [x] identifier
    - [x] basic way for test(only allow `i` this single level access) 3eef0645fa53e2a5c40e32d9f8bc53a20d5811c2
    - [x] access chain format c7766857d5adf2ea613d5f7283e9af8f24846ade
  - [x] number(int, float) 3eef0645fa53e2a5c40e32d9f8bc53a20d5811c2
  - [x] string literal e80c35ca05569ffb7dec398a281d03b33bbacaf9
  - [x] boolean literal b43e87eb6198f2446486f8095f52e73146a8d024
  - [x] left associative operator: fix bugs with 1756991704c0efaa1e676bec025370b63c4378e8
    - [x] `+` 3eef0645fa53e2a5c40e32d9f8bc53a20d5811c2
    - [x] `-` d290c4bf970707c851f3f107a4c215fce1706e69
    - [x] `*` d290c4bf970707c851f3f107a4c215fce1706e69
    - [x] `/` d290c4bf970707c851f3f107a4c215fce1706e69
  - [x] function call f89e16fa1d6e61a6f03779c5723adfc632bde472
    - [x] bug: the nesting function call can't be parsed, the problem is it should be try at the end of expression parsing d7f870ee26bfb6a5909262a5360b084bdab2c611
  - [x] list literal 8470ad8f828ae1826edc3d7adf72e391f42ed7d2
  - [x] element access d7f870ee26bfb6a5909262a5360b084bdab2c611
  - [x] force sub expression(`(expr)`) 4e9d68600ace568dbee835974eb26c12cf7c5064

### Addtional work

- [x] improve the position representation, introducing `(line, pos)` format d0fe7819a4fd0a9c1592fa85fd6a95352bfcea77

**Comment by dannypsnl** [comment]
sub task:
- [ ] improve the position representation, introducing `(line, pos)` format

**Comment by dannypsnl** [comment]
```
add :: i32 -> i32 -> i32
add x y = x + y
// compare with
add :: ('a, 'a) -> 'a
add x y = x + y
// since we don't want currying, then the currying function type do not make any sense
```

But for now, still parsing the old format, else we have to fix too many codegen codes before we sure they work with current parser
