### ISSUE TITLE
module overview

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/elz#270]
### Module, Library and using

A module is a file, for example, a module named `k`.

```
module k

foo(): void {}
```

Many modules can be grouped as a library. Library can have **internal** module which can't be accessed by other libraries.

For example, we can have a `k._internal` module in the library `k`:

```
module k._internal
```

### Semantic

- reject cyclic import
- All components in elz use the same access management way: start with `_` is private.

### TODO

- [x] lexer: token `module`, `import`
- [x] ast: `module` structure, `import` statement
- [x] syntax
  - [x] parse module(declare at the top of the file)
    ```
    module foo
    ```
  - [x] parse import statement, e.g.
    ```
    import file.util ( read_all )
    ```
- [x] semantic
  - [x] check `module`
  - [x] normalize `import`

**Comment by dannypsnl** [comment]
1. load lib file, e.g. `k.elz`
2. get directory where lib file located
3. load all files in that directory
4. emit module path for each file
5. parse files
6. create internal presentation for these modules
7. semantic check these modules

**Comment by dannypsnl** [comment]
To distinguish target is a library or a binary, the option is not required. If contains `main` is binary, else not.

**Comment by dannypsnl** [comment]
The design is too naive, for example, a module `a` use module also named `a`, so it uses `b=a` to avoid confliction. But in `b`(origin imported `a`)it uses `a::` to access its member. Therefore, conflict still there.

To solve the problem, I think **namespace** is the most simple design but powerful enough stuff.
